### ISSUE TITLE
Translation documentation

### ISSUE THREAD

**Issue by anselmdk** [silvershop/silvershop-core#546]
I feel there's missing a little bit of documentation on how we deal with translations.
As an example, I introduced a translation here:
https://github.com/silvershop/silvershop-core/blob/master/templates/Layout/Product.ss#L48

It's definitely not translated to German, but on Transifex it says German is 100% translated. I guess I forgot to run a language collector (which one?), and might have to upload the `en.yml` file to Transifex (how?). I propose we document all this, and link to it from the main `README.md` file so it's easy to find.

I'm happy do do so, just need your input, @bummzack ?

**Comment by bummzack** [comment]
English is our master language, adding the key to `en.yml` is the first step to do. I actually think it's best to just add new translation keys manually instead of using a collector… if you insist on a collector, I've used https://github.com/Zauberfisch/silverstripe-better-i18n previously.

To integrate with transifex, you need an account over there and me or mark will have to add you as a maintainer. You need a real account, using your github or other credentials (oauth) doesn't work!

You then need to [install the transifex client](http://docs.transifex.com/client/setup/), then [configure your access credentials](http://docs.transifex.com/client/config/) and use `tx push -s` to push the changed source file to transifex.

Once translations are done on transifex, you can grab the translations `tx pull -a` and commit them…

I'm also happy to do these steps. You can just update `en.yml` and I'll push the changed file to transifex.

**Comment by bummzack** [comment]
I'm sorry, above is probably not 100% accurate. You can use your Github account to sign in to transifex, you'll just have to set a password for transifex separately there (in your profile). This is the password you'll going to need to use the tx client.

**Comment by anselmdk** [comment]
Great, I'll try this out, and will document in `/docs/en/02_Customisation/01_Recipes/Multi_Language.md`

**Comment by anselmdk** [comment]
@bummzack / @markguinn could one of you guys add me to Transifex? My account ist ac@anselm.dk

**Comment by bummzack** [comment]
@anselmdk done

**Comment by anselmdk** [comment]
I just tried to document the steps. I'm getting `HttpNotAuthorized: Authorization Required` when trying to push and pull though. Any hints?

**Comment by bummzack** [comment]
Did you create the `~/.transifexrc` file with your credentials? As outlined here: http://docs.transifex.com/client/config/

**Comment by anselmdk** [comment]
Yeah, just double checked, I had misspelled my username. It works now! Closing.
