### ISSUE TITLE
Variation required message escaping quotes

### ISSUE THREAD

**Issue by asecondwill** [silvershop/silvershop-core#593]
The variation validation gives an error message such as:

`&quot;Weight&quot; is required`

The quotes should not be escaped.

**Comment by asecondwill** [comment]
I'm getting this when i have a variation set up for a product and don't select it when trying to add it to the car.

**Comment by bummzack** [comment]
I've spent some time debugging this and it's a rather tricky subject. 

The SilverStripe `Form` class encodes error messages to XML at different locations. In our case, the form has a DropDown field for the variation attribute and the form validates this field accordingly and adds it to the errors (it's getting encoded in this process, see [source](https://github.com/silverstripe/silverstripe-framework/blob/3.5/forms/Form.php#L1325)).

This is fine and works as usual, but once the validation fails, the form gets re-generated (via template) and populated with the existing error messages in the session. At that moment in time, the form no longer contains the DropDown field and the error message gets added to the outer form via `Form->setMessage`, where it get's encoded a second time! [Source](https://github.com/silverstripe/silverstripe-framework/blob/3.5/forms/Form.php#L313)

I guess this is partially related to https://github.com/silverstripe/silverstripe-framework/issues/3774 and could probably be fixed by refactoring `VariationForm`.
