### ISSUE TITLE
Whats the best way to assign a product categoory to more than one parent.

### ISSUE THREAD

**Issue by am071092** [silvershop/silvershop-core#711]
Category1
|
|------------SubCategoryA

Category2
|
|------------SubCategoryA

Is this even possible in silverstripe?

**Comment by wilr** [comment]
Hi @am071092 in this case you could try using a `VirtualPage` to link the SubCategoryA pages and see if that works in this case otherwise and you'll need to work out some other way of storing your categories (perhaps 1 level of categories and tick `Category1` and `SubCategoryA` for products. Products support being part of multiple categories.
